// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX6_g1oD1Q3lqZ4gMlK_1yvyOsU-cwj_Y',
    appId: '1:33594383922:web:6ecf314dd63a4f7019a62b',
    messagingSenderId: '33594383922',
    projectId: 'gestura-7b295',
    authDomain: 'gestura-7b295.firebaseapp.com',
    storageBucket: 'gestura-7b295.firebasestorage.app',
    measurementId: 'G-F2VJ7DHGLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRYplLWH4VM3Q-n7sYc54aXUAyIso6sL8',
    appId: '1:33594383922:android:a0444a68c1a7426e19a62b',
    messagingSenderId: '33594383922',
    projectId: 'gestura-7b295',
    storageBucket: 'gestura-7b295.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9V3FdlKDRyrhFDpfAEEaZUMxgc-IlK8M',
    appId: '1:33594383922:ios:572624097623586319a62b',
    messagingSenderId: '33594383922',
    projectId: 'gestura-7b295',
    storageBucket: 'gestura-7b295.firebasestorage.app',
    iosClientId: '33594383922-tetiavog25a1uvdcg6meaos1mrrc62m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9V3FdlKDRyrhFDpfAEEaZUMxgc-IlK8M',
    appId: '1:33594383922:ios:572624097623586319a62b',
    messagingSenderId: '33594383922',
    projectId: 'gestura-7b295',
    storageBucket: 'gestura-7b295.firebasestorage.app',
    iosClientId: '33594383922-tetiavog25a1uvdcg6meaos1mrrc62m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX6_g1oD1Q3lqZ4gMlK_1yvyOsU-cwj_Y',
    appId: '1:33594383922:web:ca9c64e01d5522ea19a62b',
    messagingSenderId: '33594383922',
    projectId: 'gestura-7b295',
    authDomain: 'gestura-7b295.firebaseapp.com',
    storageBucket: 'gestura-7b295.firebasestorage.app',
    measurementId: 'G-TF6280DS3H',
  );

}